name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build'

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: npm ci
      - name: Build
        run: npm run build

  prettier:
    runs-on: ubuntu-latest
    name: 'Prettier'
    needs: [ build ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: npm ci
      - name: Prettier
        run: npm run prettier:check

  lint:
    runs-on: ubuntu-latest
    name: 'Lint'
    needs: [ build ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    name: 'Test'
    needs: [ build ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: npm ci
      - name: Test
        run: npm run test:ci
